#!/bin/bash

. `dirname $0`/wl_defines.sh

# TODO: Check if tree already exists first
# TODO: Bail if errors
# TODO: Log output

WLROOT="/home/aas/wacom/wayland"
clone_or_update() {
	repo=$1
	dest=$(basename $repo)

	cd ${WLROOT}
	if [ $? != 0 ]; then
		echo "Error: Could not cd to ${WLROOT}.  Does it exist?"
        exit 1
	fi
	echo
	echo $dest
	if [ ! -d ${dest} ]; then
		git clone --depth=1 ${repo} ${dest}
		if [ $? != 0 ]; then
			echo "Error: Could not clone repository"
			exit 1
		fi
	fi
	cd ${dest}
	git checkout master
	if [ $? != 0 ]; then
		echo "Error: Problem checking out master"
		exit 1
	fi
	git pull
	if [ $? != 0 ]; then
		echo "Error: Could not pull from upstream"
		exit 1
	fi
	cd ${WLROOT}
}

clone_or_update https://anongit.freedesktop.org/git/wayland/wayland.git
clone_or_update https://anongit.freedesktop.org/git/mesa/drm.git
clone_or_update https://anongit.freedesktop.org/git/xcb/proto.git
clone_or_update https://anongit.freedesktop.org/git/xorg/util/macros.git
clone_or_update https://anongit.freedesktop.org/git/xcb/libxcb.git
clone_or_update https://anongit.freedesktop.org/git/xorg/proto/presentproto.git
clone_or_update https://anongit.freedesktop.org/git/xorg/proto/dri3proto.git
clone_or_update https://anongit.freedesktop.org/git/xorg/lib/libxshmfence.git
clone_or_update https://github.com/xkbcommon/libxkbcommon.git
clone_or_update https://anongit.freedesktop.org/git/mesa/mesa.git
clone_or_update https://anongit.freedesktop.org/git/pixman.git
clone_or_update https://anongit.freedesktop.org/git/cairo
clone_or_update https://git.savannah.gnu.org/git/libunwind.git
clone_or_update https://anongit.freedesktop.org/git/libevdev.git
clone_or_update https://anongit.freedesktop.org/git/wayland/wayland-protocols.git
clone_or_update https://anongit.freedesktop.org/git/wayland/libinput.git
clone_or_update https://anongit.freedesktop.org/git/wayland/weston.git

if [ ${INCLUDE_XWAYLAND} ]; then
	if [ ${WL_BITS} = "32" ]; then
		clone_or_update https://anongit.freedesktop.org/xorg/lib/libxtrans
	fi

	clone_or_update https://github.com/anholt/libepoxy
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/glproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/xproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/xcmiscproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/lib/libxtrans.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/bigreqsproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/xextproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/fontsproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/videoproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/recordproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/resourceproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/xf86driproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/proto/randrproto.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/lib/libxkbfile.git
	clone_or_update https://anongit.freedesktop.org/git/xorg/xserver.git
fi
